module.exports = exports = {
  'url-metrics': {
    'title'                         : 1,
    'url'                           : 4,
    'subdomain'                     : 8,
    'root_domain'                   : 16,
    'external_links'                : 32,
    'subdomain_external_links'      : 64,
    'domain_external_links'         : 128,
    'juice_passing_links'           : 256,
    'subdomains_linking'            : 512,
    'domains_linking'               : 1024,
    'links'                         : 2048,
    'subdomain_subs_linking'        : 4096,
    'domain_domains_linking'        : 8192,
    'moz_rank'                       : 16384,
    'subdomain_moz_rank'             : 32768,
    'domain_moz_rank'                : 65536,
    'moz_trust'                      : 131072,
    'subdomain_moz_trust'            : 262144,
    'domain_moz_trust'               : 524288,
    'external_moz_rank'              : 1048576,
    'subdomain_external_juice'      : 2097152,
    'domain_external_juice'         : 4194304,
    'subdomain_domain_juice'        : 8388608,
    'domain_domain_juice'           : 16777216,
    'canonical_url'                 : 268435456,
    'http_status'                   : 536870912,
    'subdomain_links'               : 4294967296,
    'domain_links'                  : 8589934592,
    'domains_linking_to_subdomain'  : 17179869184,
    'page_authority'                : 34359738368,
    'domain_authority'              : 68719476736
  },

  'anchor-text': {
    'phrase'                        : 2,
    'internal_pages_linking'        : 8,
    'internal_subdomains_linking'   : 16,
    'external_pages_linking'        : 32,
    'external_subdomains_linking'   : 64,
    'external_root_domains_linking' : 128,
    'internal_mozRank_passed'       : 256,
    'external_mozRank_passed'       : 512,
    'image_link'                    : 1024
  },

  'links': {
    'null'                          : 0,
    'flags'                         : 2 ,
    'anchor_text'                   : 4 ,
    'normalized_anchor_text'        : 8 ,
    'mox_rank_passed'                : 16
  },
  'linkcols': {
    'no_follow'                     : 1,
    'same_subdomain'                : 2,
    'meta_refresh'                  : 4,
    'same_ip_address'               : 8,
    'same_c_block'                  : 16,
    'spam_score'                    : 32,
    '301_redirec'                   : 64,
    '302_redirect'                  : 128,
    'no_script'                     : 256,
    'off_screen'                    : 512,
    'meta_no_follow'                : 2048,
    'same_root_domain'              : 4096,
    'img'                           : 8192,
    'feed_auto_discovery'           : 16384,
    'rel_canonical'                 : 32768,
    'via_301'                       : 65536
  }
}
